name: Azure Function Deploy With GIT.
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
          architecture: x64

      - name: Install required python modules
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt 

      - name: Zip the Azure Function Deploy folder
        run: |
          zip -r ../skills-introduction-to-github.zip ./*

      - uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
  
