on:
  push:
    branches:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: '3.12'
  functionAppName: 'func-apps'
  azureSubscription: 'BeMine-App'
  azureResourceGroup: 'rg-dfetcu'
  azureRegion: 'West Europe'

steps:
- task: UsePythonVersion@0
  displayName: 'Set Python version to $(pythonVersion)'
  inputs:
    versionSpec: '$(pythonVersion)'

- bash: |
    python -m venv .venv
    source .venv/bin/activate
    pip install --upgrade pip
    pip install -r ./requirements.txt
  displayName: 'Install Python dependencies'

- task: ArchiveFiles@2
  displayName: 'Archive function app files'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifactName: 'drop'

- task: AzureFunctionApp@2
  displayName: 'Deploy to Azure Function App'
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: '$(functionAppName)'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    resourceGroupName: '$(azureResourceGroup)'
    deploymentMethod: 'auto'
    region: '$(azureRegion)'
