on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    variables:
      pythonVersion: '3.12'
      functionAppName: 'func-apps'
      azureSubscription: 'BeMine-App'
      azureResourceGroup: 'rg-dfetcu'
      azureRegion: 'West Europe'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Python version to $(pythonVersion)
      uses: actions/setup-python@v3
      with:
        python-version: '$(pythonVersion)'

    - name: Install Python dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Archive function app files
      run: |
        zip -r $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip $(Build.SourcesDirectory)

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: drop
        path: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

    - task: AzureFunctionApp@2
      displayName: 'Deploy to Azure Function App'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(functionAppName)'
        package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        resourceGroupName: '$(azureResourceGroup)'
        deploymentMethod: 'auto'
        region: '$(azureRegion)'
